# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/             
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: webext-buildtools-chrome-crx-action
      uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.0
    # pack zip and read manifest, can be reused in the following steps
    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: 'extension'
        zipFilePath: 'build/extension.zip'
    - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      with:
        # zip file made at the packExtensionDir step
        zipFilePath: 'build/extension.zip',
        crxFilePath: 'build/extension.crx'
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }},
        # The following is optional if you need update.xml file
        updateXmlPath: 'build/update.xml',      
        updateXmlCodebaseUrl: 'http://...'





